-- Database Initialization Script
-- Generated by ProjexLight CLI Export System
-- Project: Bidwork
-- Database: postgresql
-- Auto-executed when Docker container is first created
-- Location: ./init-scripts/01-schema.sql
-- Schema Hash: e10808d43975dc40

-- ========================================
-- SCHEMA VERSION TRACKING (For Multi-Developer Sync)
-- ========================================
-- This table tracks the current schema version in your local database.
-- The MCP Schema Sync Agent uses this to detect changes and sync with ProjexLight.

CREATE TABLE IF NOT EXISTS _schema_version (
    id SERIAL PRIMARY KEY,
    schema_hash VARCHAR(64) NOT NULL,
    version INTEGER DEFAULT 1,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR(50) DEFAULT 'init'  -- 'init', 'migration', 'sync'
);

-- ========================================
-- APPLICATION SCHEMA
-- ========================================

-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: Bidwork Schema
-- Description: Auto-generated database schema for Bidwork. Generated from project description...
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255),
  password_hash VARCHAR(255),
  role VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE users IS 'Schema: Bidwork Schema - Entity: Users';

CREATE TABLE IF NOT EXISTS implement_password_hashing (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255),
  status VARCHAR(255) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE implement_password_hashing IS 'Schema: Bidwork Schema - Entity: Implement_password_hashing';

CREATE TABLE IF NOT EXISTS create_user_registration_endpoint (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255),
  status VARCHAR(255) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE create_user_registration_endpoint IS 'Schema: Bidwork Schema - Entity: Create_user_registration_endpoint';

CREATE TABLE IF NOT EXISTS create_user_login_endpoint (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255),
  status VARCHAR(255) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE create_user_login_endpoint IS 'Schema: Bidwork Schema - Entity: Create_user_login_endpoint';


-- ========================================
-- SAMPLE DATA (Optional)
-- ========================================
-- Uncomment and modify the following to add sample data:

-- INSERT INTO users (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO implement_password_hashing (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO create_user_registration_endpoint (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO create_user_login_endpoint (column1, column2) VALUES ('value1', 'value2');

-- ========================================
-- RECORD INITIAL SCHEMA VERSION
-- ========================================
INSERT INTO _schema_version (schema_hash, version, source) VALUES ('e10808d43975dc40', 1, 'init');

-- ========================================
-- SCRIPT COMPLETED
-- ========================================
